name: Checkov Checks on Terraform Code

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Tfsec Checks on Terraform Code"]
    types:
      - completed
  push:
    branches:
        - feature*
  pull_request:
    branches:
      - development      
      
permissions: read-all

jobs:
  tflint-checks:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout Repository
    - name : Check out Git Repository
      uses: actions/checkout@v3  
      
    # TFLint - Terraform Check
    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v2
    
    - name: Install Terraform plugins
      run: tflint --init
    
    - name: Lint Terraform files
      run: tflint -f compact --recursive

  tfsec-checks:
        runs-on: ubuntu-latest
        steps:
      
        # Checkout Repository
        - name : Check out Git Repository
          uses: actions/checkout@v2
        
        # Tfsec - Security scanner for your Terraform code
        - name: Run Tfsec
          uses: aquasecurity/tfsec-action@v1.0.0
      
  checkov-checks:
      runs-on: ubuntu-latest
      steps:
      
      # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v2
      
      # Checkov - Prevent cloud misconfigurations and find vulnerabilities during build-time in infrastructure as code
      - name: Run Checkov
        run: |
           docker run -t -v ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --skip-check CKV2_GHA_1
